services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
      ports:
         - 8211:8211/udp
         - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
         - 8212:8212/tcp  # REST API enabled port, enabled by default. DO NOT PORT FORWARD THIS.
      environment:
         PUID: 1000
         PGID: 1000
         PORT: 8211  # Optional but recommended
         PLAYERS: 16  # Optional but recommended
         SERVER_PASSWORD: "rw101"  # Optional but recommended
         MULTITHREADING: true
         REST_API_ENABLED: true
         REST_API_PORT: 8212
         TZ: "Asia/Bangkok"
         ADMIN_PASSWORD: "password"
         COMMUNITY: true  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         SERVER_NAME: "rw_101"
         SERVER_DESCRIPTION: "Roi et"
         CROSSPLAY_PLATFORMS: "(Steam)"
         # Game settings
         EXP_RATE: 5.0
         DEATH_PENALTY: "None"
         ENABLE_FAST_TRAVEL : true
         PAL_SPAWN_NUM_RATE: 1.0
         ENABLE_INVADER_ENEMY: false
         
      volumes:
         - data:/palworld/
         - ./mods/CreativeMenu_P.pak:/palworld/Pal/Content/Paks/~mods/CreativeMenu_P.pak
         - ./mods/Unlock World Map View_P.pak:/palworld/Pal/Content/Paks/~mods/Unlock World Map View_P.pak
         - ./mods/Xyro Fast And Better Breed Farm_P.pak:/palworld/Pal/Content/Paks/~mods/Xyro Fast And Better Breed Farm_P.pak
         - ./mods/Gantz79 Modular Mod_P.pak:/palworld/Pal/Content/Paks/~mods/Gantz79 Modular Mod_P.pak

volumes:
  data:

networks:
  default:
    external: true
    name: base